// Client interface strings (Ukrainian). Scanned by the language test.

export const T = {
  title: 'Безгомін',
  subtitle: 'Гра на двох',
  loading: 'З\'єднання…',
  reconnecting: 'Зв\'язок перервано. Відновлюємо…',
  offlineDot: 'Немає зв\'язку',
  onlineDot: 'На зв\'язку',

  codeLabel: 'Код запрошення',
  codePlaceholder: 'XXXX-XXXX',
  codeEnter: 'Увійти',
  codeHint: 'Код дає той, хто запустив гру на сервері.',

  createTitle: 'Хто ти?',
  nameLabel: 'Ім\'я',
  namePlaceholder: 'Як тебе звати',
  genderLabel: 'Як про тебе казати',
  genderM: 'Він',
  genderF: 'Вона',
  roleLabel: 'Твоя справа',
  roleHunterM: 'Ловець',
  roleHunterF: 'Ловчиня',
  roleHunterDesc: 'Ліс, звір і сліди. Бачить те, що лишається на снігу й на людях.',
  roleMakerM: 'Майстер',
  roleMakerF: 'Майстриня',
  roleMakerDesc: 'Дерево, залізо й письмо. Лагодить, будує, читає.',
  roleTaken: 'уже обрано',
  roleNote: 'Кожен із вас бачитиме своє. Розповідайте одне одному, що помітили.',
  start: 'Почати',
  claimTitle: 'Обидва місця зайняті. Хто ти?',
  claimOr: 'Уже граєш з іншого пристрою? Увійди як:',
  claimAs: 'Я —',
  back: 'Назад',

  day: 'День',
  goal: 'Мета',
  tabWork: 'Справи',
  tabNotes: 'Записи',
  tabLog: 'Журнал',
  stock: 'Комора',
  items: 'Речі',
  folk: 'Громада',
  partner: 'Поруч',
  partnerNone: 'Друге місце ще вільне',
  partnerOffline: 'не в мережі',
  partnerIdle: 'поруч',
  you: 'Ти',
  together: 'удвох',
  needBoth: 'Потрібні обоє',
  busyNow: 'Зайнято',
  questions: 'Питання',
  clues: 'Що ми знаємо',
  people: 'Люди',
  personal: 'Бачиш лише ти',
  personalShort: 'лише ти',
  emptyNotes: 'Поки що записів немає.',
  notesSearch: 'Пошук у записах',
  notesClear: 'Очистити',
  filterAll: 'Усе',
  filterMine: 'Бачу лише я',
  filterNew: 'Нове',
  newShort: 'нове',
  rec1: 'запис',
  rec2: 'записи',
  rec5: 'записів',
  noCluesYet: 'Записів ще немає',
  nothingFound: 'Нічого не знайдено',
  otherClues: 'Інше',
  emptyLog: 'Тиша.',

  next: 'Далі',
  waiting: 'Чекаємо…',
  accept: 'Іти',
  decline: 'Пізніше',
  cancel: 'Скасувати',
  minimize: 'Згорнути',
  expand: 'Розгорнути',
  scenePaused: 'Розповідь на паузі',
  combatEnemy: 'Сила',
  combatFear: 'Страх',
  combatRound: 'Хід',
  combatYou: 'Твої сили',
  combatPartner: 'Сили',
  hp: 'Сили',
  actDone: 'Кінець дії',
  sec: 'с',
  have: 'є',
  deltaBoth: 'Разом',
  soundOn: 'Увімкнути звук',
  soundOff: 'Вимкнути звук',
};

export type Strings = typeof T;
