import type { AmbientDef } from '../shared/src/content.js';

// Visual ambience only: weather per area, where fires burn, and a small accent per action.
export const ambient: AmbientDef = {
  areas: { yas: 'snow', tower: 'river', kruchi: 'cave' },
  overrides: [
    { when: { all: [{ noFlag: 'done:scn_01' }, { flag: 'candle_lit' }] }, kind: 'candle' },
    { when: { noFlag: 'done:scn_01' }, kind: 'cellar' },
  ],
  fires: {
    tower: { flag: 'built:act_42' },
    kruchi: { flag: 'built:act_64' },
  },
  actions: {
    // prologue
    act_p1: 'breath',
    act_p2: 'heart',
    act_p3: 'rummage',
    act_p4: 'flint',
    act_p5: 'rubble',
    // fire
    act_01: 'fire',
    act_02: 'fire',
    act_42: 'fire',
    act_64: 'fire',
    // home and yard
    act_03: 'rummage',
    act_13: 'rummage',
    act_09: 'bowl',
    act_54: 'care',
    act_71: 'care',
    act_61: 'salt',
    act_52: 'salt',
    act_66: 'wax',
    act_67: 'wax',
    act_77: 'wax',
    act_68: 'hive',
    act_51: 'trade',
    act_69: 'trade',
    // axe work
    act_10: 'chop',
    act_11: 'chop',
    act_48: 'chop',
    // water
    act_15: 'water',
    act_45: 'water',
    act_65: 'water',
    act_59: 'fish',
    act_78: 'fish',
    act_46: 'fish',
    act_76: 'fish',
    act_62: 'row',
    act_63: 'row',
    // pot on the fire
    act_12: 'steam',
    act_70: 'steam',
    // on foot
    act_16: 'walk',
    act_17: 'walk',
    act_22: 'walk',
    act_40: 'walk',
    act_41: 'walk',
    act_50: 'walk',
    act_58: 'walk',
    act_24: 'twigs',
    act_57: 'twigs',
    act_75: 'twigs',
    act_25: 'snare',
    act_26: 'snare',
    act_72: 'send',
    act_73: 'send',
    act_74: 'send',
    // hunting
    act_27: 'arrow',
    act_49: 'arrow',
    // iron
    act_23: 'whet',
    act_47: 'forge',
    act_21: 'scrap',
    // handiwork
    act_04: 'string',
    act_06: 'carve',
    act_08: 'carve',
    act_55: 'carve',
    act_60: 'carve',
    act_79: 'carve',
    act_07: 'rope',
    act_56: 'rope',
    // building, digging, flour
    act_05: 'build',
    act_14: 'build',
    act_18: 'build',
    act_19: 'build',
    act_20: 'build',
    act_44: 'build',
    act_53: 'build',
    act_43: 'rubble',
    act_28: 'sift',
  },
};
